// Runs at build time (see "build" script in package.json / Netlify build
// command). Reads every .ejs template and bundles its raw text into a single
// generated JS module (views-bundled.js) that gets `require`d directly.
//
// Why: Netlify Functions are bundled by esbuild, which only reliably
// includes files that are statically `require`d in code. Relying on the
// `views/` folder being present on disk at runtime (via netlify.toml's
// included_files) is fragile — path resolution inside the bundled function
// doesn't always match the original project layout. Bundling the template
// text directly into requirable JS sidesteps the whole problem.
const fs = require('fs');
const path = require('path');

const viewsDir = path.join(__dirname, '..', 'views');
const outFile = path.join(__dirname, '..', 'views-bundled.js');

const files = fs.readdirSync(viewsDir).filter(f => f.endsWith('.ejs'));
const templates = {};
for (const file of files) {
  const name = file.replace(/\.ejs$/, '');
  templates[name] = fs.readFileSync(path.join(viewsDir, file), 'utf8');
}

const banner = '// AUTO-GENERATED by scripts/build-views.js — do not edit by hand.\n// Edit the .ejs files in views/ instead, then re-run the build.\n';
const body = 'module.exports = ' + JSON.stringify(templates, null, 2) + ';\n';
fs.writeFileSync(outFile, banner + body);
console.log(`[build-views] Bundled ${files.length} templates into views-bundled.js`);

// Self-host Chart.js instead of loading it from a CDN. Some browsers block
// third-party CDN scripts (ad blockers, corporate firewalls), which made the
// "Графики" charts silently fail with "Chart is not defined". Copying the
// library into public/js/ makes it same-origin and reliable.
try {
  const chartSrc = path.join(__dirname, '..', 'node_modules', 'chart.js', 'dist', 'chart.umd.min.js');
  const jsDir = path.join(__dirname, '..', 'public', 'js');
  fs.mkdirSync(jsDir, { recursive: true });
  fs.copyFileSync(chartSrc, path.join(jsDir, 'chart.umd.min.js'));
  console.log('[build-views] Copied chart.js into public/js/');
} catch (e) {
  console.warn('[build-views] Could not copy chart.js (charts will not render):', e.message);
}

// Bundle binary assets (the Cyrillic-capable PDF font + the company logo) as
// base64 strings inside a requirable JS module. The PDF report is generated
// inside a Netlify Function, which cannot read arbitrary files from the
// public/ folder at runtime (that folder is only served statically, it is
// not part of the function's bundle) — so instead of reading files off disk,
// everything the PDF needs is embedded directly in code, same trick as
// views-bundled.js above.
try {
  const assetsOutFile = path.join(__dirname, '..', 'assets-bundled.js');
  const fontRegular = fs.readFileSync(path.join(__dirname, '..', 'fonts', 'DejaVuSans.ttf')).toString('base64');
  const fontBold = fs.readFileSync(path.join(__dirname, '..', 'fonts', 'DejaVuSans-Bold.ttf')).toString('base64');
  const logo = fs.readFileSync(path.join(__dirname, '..', 'public', 'images', 'logo.png')).toString('base64');
  const assetsBanner = '// AUTO-GENERATED by scripts/build-views.js — do not edit by hand.\n';
  const assetsBody =
    'module.exports = {\n' +
    '  fontRegular: ' + JSON.stringify(fontRegular) + ',\n' +
    '  fontBold: ' + JSON.stringify(fontBold) + ',\n' +
    '  logoPng: ' + JSON.stringify(logo) + ',\n' +
    '};\n';
  fs.writeFileSync(assetsOutFile, assetsBanner + assetsBody);
  console.log('[build-views] Bundled PDF font + logo into assets-bundled.js');
} catch (e) {
  console.warn('[build-views] Could not bundle PDF assets (PDF reports will fail):', e.message);
}
