// Runs at build time (see "build" script in package.json / Netlify build
// command). Reads every .ejs template and bundles its raw text into a single
// generated JS module (views-bundled.js) that gets `require`d directly.
//
// Why: Netlify Functions are bundled by esbuild, which only reliably
// includes files that are statically `require`d in code. Relying on the
// `views/` folder being present on disk at runtime (via netlify.toml's
// included_files) is fragile — path resolution inside the bundled function
// doesn't always match the original project layout. Bundling the template
// text directly into requirable JS sidesteps the whole problem.
const fs = require('fs');
const path = require('path');

const viewsDir = path.join(__dirname, '..', 'views');
const outFile = path.join(__dirname, '..', 'views-bundled.js');

const files = fs.readdirSync(viewsDir).filter(f => f.endsWith('.ejs'));
const templates = {};
for (const file of files) {
  const name = file.replace(/\.ejs$/, '');
  templates[name] = fs.readFileSync(path.join(viewsDir, file), 'utf8');
}

const banner = '// AUTO-GENERATED by scripts/build-views.js — do not edit by hand.\n// Edit the .ejs files in views/ instead, then re-run the build.\n';
const body = 'module.exports = ' + JSON.stringify(templates, null, 2) + ';\n';
fs.writeFileSync(outFile, banner + body);
console.log(`[build-views] Bundled ${files.length} templates into views-bundled.js`);
